---
- hosts: all

  vars:
    pip_install_packages:
      - name: docker

  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes
      become: yes

    - name: Install apps
      ansible.builtin.apt:
        pkg:
          - docker
          - docker-compose
      become: yes

    - name: Install pip and pip-packages
      import_role: 
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
      become: yes

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        group: docker
      become: yes

            
